export const tableData = [
    {
        "Id": "1",
        "CompanyName": "TCS",
        "EmploymentType": "Full-Time",
        "JobTitle": "Marketing",
        "RolesResponsibility": "Software",
        "ExperienceYear": "7",
        "Location": "Varanasi",
        "Qulification": "MCA",
        "Salary": "MCA",
        "Salary": "20000",
        "CantactNumber": "6754567897",
        "ContactEmail":"nilesh@gmail.com",
        "ContactName":"Nilesh",
    },
    {
        "Id": "2",
        "CompanyName": "Google",
        "EmploymentType": "Full-Time",
        "JobTitle": "Senior Developer",
        "RolesResponsibility": "Web Development",
        "ExperienceYear": "5",
        "Location": "Mountain View",
        "Qulification": "BCA",
        "Salary": "2000000",
        "CantactNumber": "6754567897",
        "ContactEmail":"vaishali@gmail.com",
        "ContactName":"Vaishali",
    },
    {
        "Id": "3",
        "CompanyName": "Microsoft",
        "EmploymentType": "Full-Time",
        "JobTitle": "Data Scientist",
        "RolesResponsibility": "Data Analysis",
        "ExperienceYear": "8",
        "Location": "Redmond",
        "Qulification": "MTech",
        "Salary": "192922",
        "CantactNumber": "6754567897",
        "ContactEmail":"shrikant@gmail.com",
        "ContactName":"Shrekant",
    },
    {
        "Id": "4",
        "CompanyName": "Amazon",
        "EmploymentType": "Full-Time",
        "JobTitle": "Cloud Engineer",
        "RolesResponsibility": "Infrastructure Management",
        "ExperienceYear": "6",
        "Location": "Seattle",
        "Qulification": "BTech",
        "Salary": "222232",
        "CantactNumber": "6754567897",
        "ContactEmail":"shubham@gmail.com",
        "ContactName":"Shubham",
    },
    {
        "Id": "5",
        "CompanyName": "IBM",
        "EmploymentType": "Full-Time",
        "JobTitle": "AI Researcher",
        "RolesResponsibility": "Artificial Intelligence",
        "ExperienceYear": "9",
        "Location": "New York",
        "Qulification": "MBA",
        "Salary": "2221212",
        "CantactNumber": "6754567897",
        "ContactEmail":"avtar@gmail.com",
        "ContactName":"Avtar",
    },
    {
        "Id": "6",
        "CompanyName": "Facebook",
        "EmploymentType": "Full-Time",
        "JobTitle": "UX Designer",
        "RolesResponsibility": "User Experience Design",
        "ExperienceYear": "4",
        "Location": "Menlo Park",
        "Qulification": "BSc",
        "Salary": "23232",
        "CantactNumber": "6754567897",
        "ContactEmail":"hariom@gmail.com",
        "ContactName":"Hariom",
    },
    {
        "Id": "7",
        "CompanyName": "Apple",
        "EmploymentType": "Full-Time",
        "JobTitle": "iOS Developer",
        "RolesResponsibility": "Mobile App Development",
        "ExperienceYear": "7",
        "Location": "Cupertino",
        "Qulification": "BA",
        "Salary": "67688",
        "CantactNumber": "6754567897",
        "ContactEmail":"pratik@gmail.com",
        "ContactName":"Pratik",
    },
    {
        "Id": "8",
        "CompanyName": "Intel",
        "EmploymentType": "Full-Time",
        "JobTitle": "Hardware Engineer",
        "RolesResponsibility": "Chip Design",
        "ExperienceYear": "8",
        "Location": "Santa Clara",
        "Qulification": "BCom",
        "Salary": "8898988",
        "CantactNumber": "6754567897",
        "ContactEmail":"nitesh@gmail.com",
        "ContactName":"Nitesh",
    },
    {
        "Id": "9",
        "CompanyName": "Accenture",
        "EmploymentType": "Full-Time",
        "JobTitle": "Consultant",
        "RolesResponsibility": "Business Strategy",
        "ExperienceYear": "5",
        "Location": "Bangalore",
        "Qulification": "CS",
        "Salary": "5554322",
        "CantactNumber": "6754567897",
        "ContactEmail":"deepak@gmail.com",
        "ContactName":"Deepak",
    },
    {
        "Id": "10",
        "CompanyName": "Cisco",
        "EmploymentType": "Full-Time",
        "JobTitle": "Network Engineer",
        "RolesResponsibility": "Networking",
        "ExperienceYear": "6",
        "Location": "San Jose",
        "Qulification": "IT",
        "Salary": "1111222323",
        "CantactNumber": "6754567897",
        "ContactEmail":"arpan@gmail.com",
        "ContactName":"Arpan",
    }
]